// Types
export {
  type Vec2,
  type Position,
  Direction,
  ClassType,
  type ClassStats,
  type AbilityDef,
  type BuffDef,
  type BuffState,
  type Entity,
  EntityType,
  type PlayerState,
  MobType,
  type MobState,
  type DamageEvent,
  type CooldownState,
  ChatChannel,
  type ChatMessage,
  TileType,
  type MapData,
  type SpawnPoint,
  type CharacterSummary,
  type CharacterInfo,
  // Item System
  ItemType,
  ItemRarity,
  type ItemDef,
  type ItemStats,
  type ItemUseEffect,
  type InventoryItem,
  type LootItem,
  type WorldLoot,
  // Zones
  ZoneId,
  type ZoneMetadata,
  type Portal,
} from './types.js';

// Constants
export {
  TICK_RATE,
  TICK_INTERVAL,
  TILE_SIZE,
  MAP_WIDTH,
  MAP_HEIGHT,
  ISO_TILE_WIDTH,
  ISO_TILE_HEIGHT,
  PLAYER_SPAWN_X,
  PLAYER_SPAWN_Y,
  RESPAWN_TIME,
  AUTO_ATTACK_RANGE_MELEE,
  AUTO_ATTACK_RANGE_RANGED,
  AGGRO_RANGE,
  LEASH_RANGE,
  MOB_PATROL_RANGE,
  HEALTH_REGEN_RATE,
  MANA_REGEN_RATE,
  SAY_RANGE,
  MAX_CHAT_LENGTH,
  CHAT_RATE_LIMIT,
  MAX_CHARACTERS_PER_ACCOUNT,
  MIN_USERNAME_LENGTH,
  MAX_USERNAME_LENGTH,
  MIN_PASSWORD_LENGTH,
  MIN_CHARACTER_NAME_LENGTH,
  MAX_CHARACTER_NAME_LENGTH,
  SERVER_PORT,
  MAX_PLAYERS,
  CLASS_STATS,
  CLASS_COMBAT_CHANCES,
  CRIT_MULTIPLIER,
  RANGED_MISS_CHANCE,
  CLASS_ABILITIES,
  MOB_DEFINITIONS,
  type MobDef,
  XP_BASE,
  XP_EXPONENT,
  LEVEL_CAP,
  xpForLevel,
  LEVEL_STAT_SCALING,
  type LevelStatScaling,
  BUFF_DEFINITIONS,
  ABILITY_BUFF_MAP,
  // Mob Abilities
  type MobAbilityDef,
  MOB_ABILITIES,
  MOB_ABILITY_MAP,
  // Item System
  INVENTORY_SIZE,
  LOOT_EXPIRY_MS,
  LOOT_KILLER_ONLY_MS,
  LOOT_PICKUP_RANGE,
  PORTAL_USE_RANGE,
  MOB_SEPARATION_DISTANCE,
  MOB_SEPARATION_EPSILON,
  MOB_SEPARATION_PUSH_FACTOR,
  ITEM_DATABASE,
  type LootTableEntry,
  MOB_LOOT_TABLES,
  // Zones
  ZONE_METADATA,
  ZONE_PLAYER_SPAWNS,
  ZONE_PORTALS,
} from './constants.js';

// Protocol
export {
  ClientMessageType,
  type RegisterMessage,
  type LoginMessage,
  type CreateCharacterMessage,
  type SelectCharacterMessage,
  type DeleteCharacterMessage,
  type LogoutMessage,
  type JoinMessage,
  type MoveMessage,
  type StopMoveMessage,
  type AttackMessage,
  type UseAbilityMessage,
  type SelectTargetMessage,
  type ChatClientMessage,
  type PingMessage,
  type ClientMessage,
  ServerMessageType,
  type RegisterSuccessMessage,
  type RegisterFailedMessage,
  type LoginSuccessMessage,
  type LoginFailedMessage,
  type CharacterCreatedMessage,
  type CharacterCreateFailedMessage,
  type CharacterDeletedMessage,
  type WelcomeMessage,
  type WorldStateMessage,
  type PlayerJoinedMessage,
  type PlayerLeftMessage,
  type PlayerMovedMessage,
  type MobMovedMessage,
  type DamageDealtMessage,
  type EntityDiedMessage,
  type EntityRespawnedMessage,
  type AbilityCastMessage,
  type CooldownUpdateMessage,
  type BuffAppliedMessage,
  type BuffRemovedMessage,
  type ChatReceivedMessage,
  type LevelUpMessage,
  type MapDataMessage,
  type PongMessage,
  type ErrorMessage,
  type ServerMessage,
  // Zone messages
  type UsePortalMessage,
  type ZoneChangedMessage,
  // Item System – Client
  type PickupItemMessage,
  type DropItemMessage,
  type MoveItemMessage,
  type UseItemMessage,
  // Item System – Server
  type InventoryUpdateMessage,
  type LootSpawnedMessage,
  type LootDespawnedMessage,
  type LootPickedUpMessage,
} from './protocol.js';

// Utils
export {
  worldToScreen,
  screenToWorld,
  distance,
  normalize,
  vectorToDirection,
  lerp,
  generateId,
} from './utils.js';
