name: MegaLinter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
